### ISSUE TITLE
Tilesprite with non integer width throws error

### ISSUE THREAD

**Issue by hackhat** [photonstorm/phaser#3913]
Code: `scene.add.tileSprite(midpoint.x, midpoint.y, 64.5, 64, 'pipe');`

"phaser": "3.12.0-beta2",

Error:

```
TypeError: this.frame.resize is not a function

node_modules/phaser/src/gameobjects/tilesprite/TileSprite.js:473
  470 |     canvas.width = this.width;
  471 |     canvas.height = this.height;
  472 | 
> 473 |     this.frame.resize(this.width, this.height);
  474 | }
  475 | 
  476 | if (!this.dirty || this.renderer && this.renderer.gl)
```

**Comment by imilo** [comment]
Same error during window resize, it stops the game completely

**Comment by photonstorm** [comment]
There is no `frame.resize` method, which is the real cause of this error, not the floats. The floats could be rounded internally but there's no need as it works with them (try it in 3.11 to see).

Will remove the resize call.

**Comment by hackhat** [comment]
> There is no frame.resize method, which is the real cause of this error, not the floats. The floats could be rounded internally but there's no need as it works with them (try it in 3.11 to see).

So how come if I do Math.round before it works just fine?

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
