### ISSUE TITLE
DragonBones

### ISSUE THREAD

**Issue by MadDogMayCry0** [photonstorm/phaser#5371]
Hello.

I've been fixing some bugs in dragonbones https://phaser.discourse.group/t/dragonbones-improvments/7673. 

Fixed: inverse kinematics bugs, changing draw ordering in animation, second scene armature bug, second scene animation bug, zero frame Positive IK . All works good in 3.2x.

Then I found those parts of the code that were responsible for meshes, and decided to try the new mesh object in Beta 9. I connected a new library and got the following error.
"dragonBones.js:129 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at __extends (dragonBones.js:129)"

This line:
r.prototype = e.prototype, t.prototype = new r();

Please help get this plugin works on 3.5.0 Beta-9 that i can continue trying to make the meshes works

In case you decide to help. 
https://phaser.discourse.group/uploads/short-url/wIGXSybkO88DE5cxjhTIXh4DIZ2.js

Empty meshes are connected and the necessary code has already been fixed. We need to set it to 3.5 and connect new Mesh object, and then the vertices and indices to the mesh. Anchors contain everything.

////////////////////////////// MESH PLACEHOLDER FUNCTION
////////////////////////////// MESH PLACEHOLDER
////////////////////////////// MESH DISPLAY
////////////////////////////// MESH DEFORMATION
////////////////////////////// MESH DEFORMATION IN REALTIME

**Comment by kainage** [comment]
It's because `Phaser.Renderer.WebGL.Pipelines.TextureTintPipeline` is no longer a thing in 3.50. Try swapping it out for `Phaser.Renderer.WebGL.Pipelines.MultiPipeline`

**Comment by MadDogMayCry0** [comment]
> MultiPipeline
Thx, now it's shows new one
dragonBones.js:16287 Uncaught TypeError: renderer.hasPipeline is not a function
from
if (!renderer.hasPipeline('PhaserTextureTintPipeline'))
                            renderer.addPipeline('PhaserTextureTintPipeline', new phaser.pipeline.TextureTintPipeline({ game: game, renderer: renderer }));

**Comment by kainage** [comment]
So all those have changed to `renderer.pipelines.has`, `renderer.pipelines.add` etc. You need to change all the places that use pipelines as well.

Not sure about the mesh stuff, haven't messed around with that.

**Comment by MadDogMayCry0** [comment]
> So all those have changed to `renderer.pipelines.has`, `renderer.pipelines.add` etc. You need to change all the places that use pipelines as well.
> 
> Not sure about the mesh stuff, haven't messed around with that.

Thx you for help! It's helps alot!
About meshs. I meand - Mesh Game Object - New Features, Updates and API Changes.
from https://github.com/photonstorm/phaser/releases/tag/v3.50.0-beta.9
Maybe you know how to create such an object on stage?

**Comment by photonstorm** [comment]
This issue has been mentioned on **Phaser**. There might be relevant details there:

https://phaser.discourse.group/t/dragonbones-improvments/7673/10

**Comment by MadDogMayCry0** [comment]
> This issue has been mentioned on **Phaser**. There might be relevant details there:
> 
> https://phaser.discourse.group/t/dragonbones-improvments/7673/10

@photonstorm amm. Yea, this topic is mine too. And i'm stuck with NEW MESH Object. How to create this Mesh on scene? Can i find API for Beta-9 somewhere?

**Comment by MadDogMayCry0** [comment]
Ok, i found it on pjaser.js
function Mesh (scene, x, y, texture, frame, vertices, uvs, indicies, containsZ, normals, colors, alphas)
i'll try tomorow.

**Comment by MadDogMayCry0** [comment]
@photonstorm 

vertices - [149.89999389648438, -56.5, 178.77999877929688, 99.86000061035156, -18.260000228881836, -25.43000030517578, 10.630000114440918, 130.9199981689453]
uvs - [0.541015625, 0.2587890625, 0.6962890625, 0.2587890625, 0.541015625, 0.42578125, 0.6962890625, 0.42578125]
indices - [0, 1, 2, 1, 3, 2]

mesh.addVertices(vertices, uvs, indicies);

**phaser.js:30231** Uncaught TypeError: Cannot read property 'transformCoordinatesLocal' of undefined

```Javascript
 transformCoordinatesLocal: function (transformMatrix, width, height, cameraZ)
    {
        this.vertex1.transformCoordinatesLocal(transformMatrix, width, height, cameraZ);
        this.vertex2.transformCoordinatesLocal(transformMatrix, width, height, cameraZ);
        this.vertex3.transformCoordinatesLocal(transformMatrix, width, height, cameraZ);

        return this;
    },
```

Pls, help!

**Comment by MadDogMayCry0** [comment]
Ohh, i still can't get new Mesh to work.

https://doctoral-arrangemen.000webhostapp.com/ball/ball.html

Pls, take a look on source. It's regular atlas with no dragonbones plugin.
```Javascript
const vertices = [
        -30, 28,
        30, 28,
        -30, -28,
       30, -28
      ];
     
      const uvs = [
        0, 1,
        1, 1,
        0, 0,
        1, 0
      ];
     
     const indices = [ 0, 2, 1, 2, 3, 1 ];
	var mesh = new Phaser.GameObjects.Mesh(this, 400, 400, "texture", "ball", vertices, uvs, indices);
```

But nothing on the screen.
Pls, tell me whats wrong?

**Comment by MadDogMayCry0** [comment]
ping

**Comment by photonstorm** [comment]
Closing as it's a duplicate of #5380.

**Comment by photonstorm** [comment]
This issue has been mentioned on **Phaser**. There might be relevant details there:

https://phaser.discourse.group/t/nineslice-ninepatch-in-phaser-3-50-beta/8174/2
