### ISSUE TITLE
TypeScript compiler error when adding a layer to a layer

### ISSUE THREAD

**Issue by PhaserEditor2D** [photonstorm/phaser#5459]
## Version

* Phaser Version: 3.50.0

* Operating system: Linux

* TypeScript: 4.0.5 

## Description

The `Phaser.GameObjects.Layer` class doesn't extend `Phaser.GameObjects.GameObject` and it creates TypeScript compiler errors.

## Example Test Code

```typescript
class DemoLayer extends Phaser.Scene {

	create() {

		const layer1 = this.add.layer();

		const layer2 = this.add.layer();

		layer1.add(layer2); // error, GameObject expected

		this.sys.displayList.add(layer1); // error, GameObject expected

		this.add.existing(layer1); // error, GameObject expected
	}
}
```

## Additional Information

You can test this project:

[LayerCompilerError.zip](https://github.com/photonstorm/phaser/files/5720818/LayerCompilerError.zip)

Unzip it and run:

```bash
$ cd LayerCompilerError
$ tsc
```

You will get the following errors:

```
main.ts:9:14 - error TS2345: Argument of type 'Layer' is not assignable to parameter of type 'GameObject'.
  Type 'Layer' is missing the following properties from type 'GameObject': parentContainer, tabIndex, input, body, and 14 more.

9  	layer1.add(layer2);
   	           ~~~~~~

main.ts:11:28 - error TS2345: Argument of type 'Layer' is not assignable to parameter of type 'GameObject'.

11  	this.sys.displayList.add(layer1);
    	                         ~~~~~~

main.ts:13:21 - error TS2345: Argument of type 'Layer' is not assignable to parameter of type 'GameObject'.

13  	this.add.existing(layer1);
    	                  ~~~~~~


Found 3 errors.

```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by PhaserEditor2D** [comment]
Not working in 3.52.0:

```
main.ts:9:14 - error TS2345: Argument of type 'Layer' is not assignable to parameter of type 'GameObject'.
  Type 'Layer' is missing the following properties from type 'GameObject': eventNames, listeners, listenerCount, emit, and 6 more.

9  	layer1.add(layer2);
   	           ~~~~~~

main.ts:11:28 - error TS2345: Argument of type 'Layer' is not assignable to parameter of type 'GameObject'.

11  	this.sys.displayList.add(layer1);
    	                         ~~~~~~

main.ts:13:21 - error TS2345: Argument of type 'Layer' is not assignable to parameter of type 'GameObject'.

13  	this.add.existing(layer1);
    	                  ~~~~~~


Found 3 errors.
```

I think the problem now is that the `EventEmitter` methods are not included in the typescript defs.
