### ISSUE TITLE
require('phaser') with Browserify throws error: Error: Cannot find module './Scalar'

### ISSUE THREAD

**Issue by totty90** [photonstorm/phaser#1186]
I've also got these errors:

 - Error: Cannot find module './Scalar'
 - Error: Cannot find module './Line'

**Comment by photonstorm** [comment]
This feature request has been moved to the [Phaser 3 feature list](http://www.html5gamedevs.com/topic/7949-the-phaser-3-wishlist-thread) (so is being closed here)

**Comment by sompylasar** [comment]
@photonstorm Why a forum thread? It's not trackable... The feature requests would better be GitHub issues marked with a label and a milestone.

**Comment by photonstorm** [comment]
I don't want v3 clogging up the v2 repo (it has its own repo for that). I use the issues list as a bug tracker and it should be as close to zero as I can ever get it. I know some projects like to use it as a "todo" list as well, but I don't, sorry.

**Comment by luckylooke** [comment]
@nesukun hi! I was trying to use your workaround https://github.com/photonstorm/phaser/issues/1186#issuecomment-62481186 but when I am trying to reference phaser like this: require('phaser'); It returns empty object :/ Could you share working example please? Thanks

**Comment by the-simian** [comment]
I have a working webpack example here: https://github.com/the-simian/phaser-example

**Comment by sompylasar** [comment]
@the-simian Funny I did similar loader but haven't published to GitHub yet.

**Comment by the-simian** [comment]
@sompylasar I initially had not published it, but I decided to so I could go ahead and start keeping it handled with semver. I feel like its a bit kludgy- but it does allow a full use of webpack, in the way webpack was intended. Most of the browserify/webpack  implementations I saw don't actually use npm for phaser, but keep a local module. I was trying to get away from that.

When I have time I am going to update the loaders to work with 2.3.x, as It does break right now (only works on 2.2.x).

This was the output of the slush-phaser-webpack scaffold I am using for my own purposes, but have opened for anyone to use. Its still under development, right now. I can see from this thread, the solutions are very similar (the find and replace stuff). I can see you wrote this much earlier than I did - Do you want to be listed as an author?

**Comment by sompylasar** [comment]
@the-simian It's not rocket science actually, so I don't think listing me as author is necessary. But I really appreciate the suggestion!

Currently I've got no access to my repo, but I'll be glad to share what I've done (I don't remember if I made it compatible with 2.3.x, but I was targeting the latest release as of the time I did this).

**Comment by the-simian** [comment]
@sompylasar Thanks for your input, thusfar! 

In case you're curious, the slush scaffold I've been working on is here : https://github.com/the-simian/slush-phaser-webpack

If you, at any point get things working with 2.3.x before I do,  we can just get it into the shim and both use it!

**Comment by sompylasar** [comment]
@the-simian Thanks for pointing to https://github.com/slushjs/slush , haven't heard about it before.

**Comment by hayesmaker** [comment]
what is the point of the umd definitions in phaser if the thing only works reliably as a globally exported variable anyway?  

phaser is broken in requirejs and browserify currently (v2.3.0) either ```p2 is undefined``` (requirejs) or ```cannot find module ../collisions/AABB/``` or something similar with Browserify (even with the shim workaround)

**Comment by the-simian** [comment]
@hayesmaker This shim workaround was for v 2.2.x. I had actually published a shim, and [I deprecated it last night, since I got it working otherwise](https://github.com/the-simian/phaser-shim-loader).

You can see a working version of this with the [`slush-phaser-webpack`](https://www.npmjs.com/package/slush-phaser-webpack) project. Just install that and scaffold fo a working example.

If you don't want to do that- here's what you *can* do now

You can also include the correct build criteria yourself:

This can be achieved by simply including the dependencies that are necessary for Phaser to work:

```js
global.PIXI = require('pixi.js');
global.p2 = require('p2');
global.Phaser = require('phaser')

```

You will need to use the correct versions of both pixi and p2. At the imte of this writing, for `phaser@2.3.0` uses

```js
{
  "phaser": "2.3.x",
  "pixi.js": "2.x.x"
  "p2": "0.6.x",
}
```

Also be aware that the npm module [`pixi`](https://www.npmjs.com/package/pixi) is the *wrong module*, you want [`pixi.js`](https://www.npmjs.com/package/pixi.js), the official module

**Comment by hollowdoor** [comment]
Did phaser ever work with browserify?

**Comment by konsumer** [comment]
It worked on my trimmed fork, and it sounds like maybe others git it working.

**Comment by nesukun** [comment]
Definitely not out of the box. Various methods can be used as you can see in this very thread. But no official support for any of them, so work might need to be done when phaser is updated (that's why some of the solutions exposed here won't work anymore, including mine)

**Comment by the-simian** [comment]
@hollowfork I got phaser working in webpack. If you look for slush-phaser-webpack,  you can just generate a project. I'm still adding features, but it is stable

**Comment by konsumer** [comment]
The basic strategy for me was to add `require` statements in everything for internal/external dependencies in each file, and monkey-patch the global-cached phaser object. I trimmed it because that sort of methodology obviates the need for all the concat/header/footer stuff. I could work on it again, without trimming so much. I just wanted a clean repo to use in other projects.

**Comment by hollowdoor** [comment]
The easiest would probably be to concat everything from the `src` folder into a fresh module, but I don't know what order the dependencies are in.

**Comment by sompylasar** [comment]
It's already half-concatenated half-browserified. The easiest is patching
via string replacement. The easiest is not the best. The best would be to
NOT concat everything, but split and make the sources work in a
CommonJS-only environment with NO global variables at all. Then make a
build script that glues the modules together for the browser (via
browserify or webpack) for someone who does not have a build step in their
apps.
30.05.2015 5:25 пользователь "hollowdoor" <notifications@github.com>
написал:

**Comment by the-simian** [comment]
@sompylasar I was doing as you described with the string replacement on the `webpack-phaser-shim` module (and I had also seen you do too).

I deprecated that with v 2.2.3; If you can stomach a couple modules being attached to global.Module, then it works really well with webpack now. I would assume browserify too, since they are similar in this respect. You might have to use the browserify shim modules; however, to make things work correctly.

**Comment by sompylasar** [comment]
Everything we did is a workaround for the incomplete CommonJS support. I
think this is what should be fixed, not worked around.
30.05.2015 20:03 пользователь "Jesse Harlin" <notifications@github.com>
написал:

**Comment by hollowdoor** [comment]
@sompylasar I know what you're saying, but you're speaking of an ideal situation that is being solved in Phaser3. All I want now is an entry point that works. Concatenation with an umd at the end  would achieve that best in my opinion. No need to re-engineer the whole thing. And globals don't make me worry all that much. As long as I know which ones are there they won't hurt my feelings.

I haven't found any browserified files in the src folder. The build has them, but I'm not sure where they come from.

**Comment by konsumer** [comment]
It's totally doable with just browserify, and doesn't require re-engineering, just tracking of internal/external deps, properly. Please see https://github.com/notnullgames/phaser

**Comment by the-simian** [comment]
@sompylasar , @hollowdoor  ...sorry I was unclear.. I mean I am actually not using the shim anymore, as of v 2.2.3, it works with webpack. See full explanation here https://github.com/photonstorm/phaser/issues/1186#issuecomment-104306080

I was going to go make a fork and a PR, but they had already added the code in.

**Comment by hollowdoor** [comment]
@konsumer interesting. I haven't tried yet, but can specific objects be loaded with your solution safely? Is it just a matter of looking at the errors to see which dependencies are missing? It looks like the ./Phaser file import is everywhere.

I did get it to browserify by the way. It's 787.7 kB minified FYI.

To tell you the truth I'd rather resolve system shims on my own so your version is fine.

Maybe you should publish a scoped phaser to npm. Unless you have, and the readme reads wrong.

**Comment by hollowdoor** [comment]
@konsumer 
Oh freakin cool! I just did this with browserify, and babelify. It compiled just fine using your version of phaser.

```javascript
import BitmapData from 'phaser';

export default class DebugLines extends BitmapData {
    constructor(game, grid, w, h){
        w = w || 800;
        h = h || 600;
        super(game, "debugLine",w, h);
        
        
        this.addToWorld(0, 0);
        this.ctx.strokeStyle = '#ff0000';
        this.ctx.lineWidth = 1;
        for(var i=40; i<w; i=i+40){
            this.ctx.beginPath();
            this.ctx.moveTo(i, 0);
            this.ctx.lineTo(i, h);
            this.ctx.stroke();
            
        }
        
            
        for(var j=40; j<h; j=j+40){
            this.ctx.beginPath();
            this.ctx.moveTo(0, j);
            this.ctx.lineTo(w, j);
            this.ctx.stroke();
        }
    }
}
```

Maybe I have been thinking about phaser modules the wrong way. I still have an glimmer of hope phaser2 gets better module support in this main branch.

**Comment by hollowdoor** [comment]
Looks like a spoke too soon because now I'm getting this error. `TypeError: this.texture.baseTexture.dirty is not a function`. I can't start an `issue` because this version of Phaser is not official. Maybe I'll try the forums, but I doubt it's a universal problem that will fit the official Phaser release.

**Comment by konsumer** [comment]
I'm willing to put more work into the official version, especially if the official plan is to replace the concat/header/footer build stuff. Should I fork from `dev` maybe with a name like `commonjs`?

**Comment by nesukun** [comment]
If I recall correctly, at least in phaser 2.x.x there is no intention to support broserify/webpack. I think I remember some forum thread in which @photonstorm  stated that this kind of support wouldn't happen unless other did it, didn't mess with the way he works and didn't break anything.

Phaser 3 is another beast completely and modules support will probably (still nothing set in stone if I'm correct) come as a given as it "will be" (Again, nothing is set in stone AFAIK) written in ES6 / TS 2.0.

I love the work you guys are putting in enabling require-style modules support, but I don't know if its worth it, considering that no current projects could benefit of it as its not yet done 100%, it's a fork, therefore it will need to be synchronised with the original or will be obsolete, and maintenance burden will ever increase.

Again, thanks for the effort. Just leaving my thoughts here.

**Comment by nesukun** [comment]
> You will need to use the correct versions of both pixi and p2. At the time of this writing, for phaser@2.3.0 uses

If I'm not mistaken, Phaser doesn't use the official PIXIbuilds OOB, the one included in Phaser is modified. This could be outdated information.

**Comment by hollowdoor** [comment]
@konsumer Do you want to add to this branch, or start your own? Are you talking about Phaser2, or 3?

Now if the objective is to get the `commonjs` version into this dev branch I think it can be done if the `requires`, and `exports` you have in https://github.com/notnullgames/phaser were somehow templated into the js files using the `Gruntfile` then that would be a non-breaking solution that would probably work as long as the dependencies line up, and `require('phaser')` worked as if there was nothing changed at all. I would use this **specialty** build being the current `commonjs` doesn't work anyway.

I don't know if I'll contribute, but I am looking at the Phaser source. :)

@nesukun Maybe that's why I got an error about `baseTexture.dirty` not being a function.

**Comment by the-simian** [comment]
@nesukun actually I didn't know that, I hadn't gotten any errors yet!

I looked in the source code to match version numbers, and that's where I came up with that particular package. If what you're saying is true I'll need to modify the build.

**Comment by konsumer** [comment]
I'm just talking about whatever is in master/dev which according to the package.json in both is 2.X.X. Is 3 somewhere else?

I disagree about hacky templating and grunt to build it. It's not needed at all. A single browserify command can assemble it for everyone without a template, once all the deps are tracked correctly (as in my fork.) The result can be stored in git, if you really need that, but I'd recommend ignoring built files, and just build when needed for CDN/release.

**Comment by the-simian** [comment]
@konsumer since v 2.3.x I'm not using the hack/shim anymore either,as I mentioned. There is a gulp task, but it simply calls browserify.

**Comment by hollowdoor** [comment]
@konsumer 3 is somewhere else. On grunt Maybe. I was just thinking of pushing back to this main fork, but not changing tons of files by hand. Just to get those `requires`, and `exports` like what you have without changing the the files in `src`. Then let browserify do it's thing just like what can be done with your fork. That way there's only the build script to maintain. I guess templates aren't hacky to me. I've been wrong before. Browserify is kind of hacky by the way. ;)

**Comment by hollowdoor** [comment]
@the-simian It still doesn't work for me for some reason. You say you're using webpack, or browserify?

**Comment by the-simian** [comment]
@hollowdoor - webpack, but they should respond similarly. what's breaking? you can give the `slush-phaser-webpack` a shot, I've been working on that when I can. Might try swapping out webpack with browserify and see what happens


```sh
npm install -g slush-phaser-webpack
mkdir browserify-example-slush-phaser
cd browserify-example-slush-phaser
slush phaser-webpack
```

Then after that, swap out webpack with browserify, see what happens. Id' expect it to basically work.

**Comment by konsumer** [comment]
Cool, my main point was working CommonJS obviates the need for templates/header/footer/etc. With a CommonJS system, people are free to use whatever build system they like in their own project (webpack, browserify, etc.) If @photonstorm wants to use webpack or any other CommonJS tool for this project's builds (for CDN and release) that really doesn't affect me, as long as the CommonJS is functional. I can pick and choose the files I want in my own project's build.

@hollowdoor the requires & exports need to be in the files in `src` otherwise it's a mega-hack, in my opinion. I disagree that browserify is hacky. It does 1 thing, really well: build a pile of CommonJS files that are properly formatted into a js file.  WIthout templates, using different entry-point files, you can make a million permutations of this project (selecting different physics engines, no physics, leave out whatever you don't need, etc.) This is not possible if a build-step using templates is required. I'm not advocating for browserify anyway, it's just what I use personally in my projects, that will depend on phaser, but users can use anything that works with CommonJS (there are a lot of tools for this.)

**Comment by nesukun** [comment]
@konsumer, Phaser 3 is in its ver early stages, being worked on here: https://github.com/photonstorm/phaser3

There is also some discussion in the forums:
http://www.html5gamedevs.com/topic/7949-the-phaser-3-wishlist-thread/
http://www.html5gamedevs.com/topic/13599-reconsidering-building-phaser-3-in-typescript/

**Comment by konsumer** [comment]
@nesukun ah, cool. thanks!

**Comment by hollowdoor** [comment]
@konsumer Hm. If you're saying remake Phaser in CommonJs', and just browserify/webpack compile a stand alone Phaser for regular script links, and leave it as modules for the rest of us that sounds good. I was concerned that would be too much of an overhaul for photonstorm, but if it works like usual that's not breaking. I would be all for that personally.

@the-simian I might give slush a look, but I'd still like to have some module consistency in the main fork.

**Comment by konsumer** [comment]
@hollowdoor Should work the same,  and if it'll get used,  I'll even do the work. I'm not sure what yer issue is,  but it may be upstream or I forgot a require somewhere.

**Comment by hollowdoor** [comment]
@konsumer It's all good. I'll just watch what you're doing. Large projects can wait for modules. I have several that have gotten out of hand, and modules would help quite a bit. Walls of code lines that make me blurry eyed. If I think I can help on the fork I lend a hand.

I think my issue is a missing PIXI method.

**Comment by the-simian** [comment]
@hollowdoor try to require the  PIXI that is located in the `node_modules` of Phaser.

>I might give slush a look, but I'd still like to have some module consistency in the main fork.

Slush is just a thing that kicks off gulp processes. I has nothing to do (or not to do) with module consistency. I actually have no idea what you mean by this sentence. The included version of phaser in that generator is based on the main fork, straight off of npm. I am suggesting using it, because you can go from a working build (webpack) to a working build (browserify) without spending too much more time stumbling in the dark. They should treat the modules the same, as I said- but you might need to include `browserify-shim` (just like if you were shimming angular or jQuery)

I also agree with @konsumer that browserify is by *no* means hacky. I use browserify at work (I actually architected our modern build system) and I use webpack in some personal projects. They're both very good, and the differences aren't so great that one is clearly superior to the other. They both build commonJs modules, and get the job done. Browserify might require the `browserify-shim` plugin in order to handle some global libs. I  agree with @Konsumer that a full on CommonJs system for Phaser would be ideal, but thankfully in 2.3.x somone added the exports code at the base of the main file. Yes, its already built- but it does at least work with both browserify and webpack. It did not work in 2.2.x without some bad fixes. I have abandoned those shims, moving forward they aren't necessary. The current version does not break build, even if it is less than ideal.

**Comment by hollowdoor** [comment]
@the-simian When I use 2.3.x it breaks with a ton of not found require errors. I've read the file with the exports code. I npm installed it, and it's still not compiling with browserify.

The module consistency I was talking about is what the main Phaser has, or doesn't have as the case may be. There are files with relative requires that aren't relative any more in the concatenated module of Phaser. I'm going to try again, but my last try was just a few days ago so I don't foresee any changes. Call it a personal preference, but I'd rather just have something that works. I already have several mostly completed projects. It would not be a problem to transfer those to modules.

The only thing I'm worried about is Rich has expressed dislike for browserify in the html5gamedevs forums. Also photonstorm doesn't want any code changes to mess up their work flow. Another build step for modules is something that would stall a work flow. That's why I was talking with @konsumer about templating the exports in because a global change to modules in the main source would require a build step for the main Phaser devs. They obviously don't want that. Even though I'm sold on CommonJs in Phaser not every one agrees it's the best way.

I'm of the opinion that Phaser was developed with a diverging dependency graph mind set like most older javascript libraries. Modules are a more convergent mindset so while modules can benefit any project in Phaser they would clash a little bit. Especially at the size of the current code base. That's just my opinion. :)

**Comment by hollowdoor** [comment]
I think I just figured out how to fix it. I feel sort of stupid. There are really only two problems.

1. The requires in the **build/phaser.js** are browserified versions of modules so they need to be **derequired**.
2. The check for `require('ng.gui')` needs to be something else like others said require.resolve('ng.gui').

That would probably get Phaser 95% working with whatever commonjs bundlers there are.

Also I don't understand how PIXI, and p2 are undefined in **build/phaser.js** when Phaser is a module, and running the same as a script link still works.

**Comment by konsumer** [comment]
The thing about these libs that use this old monolithic use-script-tags approach is that they are fairly easy to convert to CommonJS. Basically they all monkey-patch a primary namespace, and since CommonJS uses a single cached object for requires, you just need the requires at the top. Very easy.

**Comment by hollowdoor** [comment]
@konsumer Though what you said is true I'm not sure what you're getting at.

BTW there is a ***pixi.js** file in the **phaser/dist/modules** folder that will fix this error `TypeError: this.texture.baseTexture.dirty is not a function` if you put that in your fork at https://github.com/notnullgames/phaser instead of `var PIXI = require('pixi.js');`. I believe **dist** is created by the grunt file as a prepublish so you have to get **phaser/dist/modules/pixi.js** from Phaser on npm. Unless you want to put module.exports in all those pixi files in src that is, or run that grunt file manually to get pixi out of it.

**Comment by hollowdoor** [comment]
@konsumer Oh now I understand. Yeah. I was thinking in terms of the set up that photonstorm has right now. The clash is really a mind set. I had to pick up the pieces of my brain after trying to understand modules back in the day when I was studying python. Now that I do understand them I can't get enough of them. They're almost too easy. I'd like to see them work right in Phaser. Hopefully Phaser3 will do it right. Not that I don't appreciate the work every one is doing on Phaser, and how awesome it is as a game framework.

**Comment by photonstorm** [comment]
Just to say that I'm preparing 2.4 for release, so if anyone reading this wants or needs to get more changes in to make your module life easier, now is the time to submit PRs. I merged in one tonight that fixed the require issue with NW.

Also just to add that Phaser doesn't use _any_ official release of Pixi any longer. We have diverged too far from the v2 codebase with our own fixes and updates. So if you're doing anything that is requiring Pixi from npm you'll need to change that.

**Comment by konsumer** [comment]
Is the version use [photonstorm/pixi.js](https://github.com/photonstorm/pixi.js)? If so, maybe this should be tracked in `package.json`. You can track it like this:

```json
{
  "dependencies": {
    "pixi.js": "git://github.com/photonstorm/pixi.js"
  }
}
```

I wonder if that project doesn't have it's own CommonJS issues, though.

**Comment by photonstorm** [comment]
No it doesn't use that fork any longer. It's a custom version specifically for Phaser, and is part of the core code base. I guess technically I could move it out to its own repo, but it's utterly useless on its own so I'm not sure it's worth the effort.

**Comment by sompylasar** [comment]
@photonstorm It's more important to make pixi.js a CommonJS-compatible module, and make the rest of the codebase depend on it. Avoid resolving it via global variables, use `require`. You could then either use relative path require or use it as an [npm local path dependency](https://docs.npmjs.com/files/package.json#local-paths) and require by module name.

**Comment by photonstorm** [comment]
I'm afraid I'm not willing to spend any time doing that. It would require rewriting a good chunk of Pixi v2, which isn't a sensible use of my time.

**Comment by nesukun** [comment]
I wonder if just adding a reference to PIXI in the exported Phaser. That way, CJS users can do 'var PIXI = require("phaser").PIXI;' and grab the reference without using globals or having to heavily modify the way Phaser is built.

**Comment by photonstorm** [comment]
Sounds better to me. If someone wants to go ahead and submit a PR that gets it working I'll happily merge. I reckon I've another couple days of testing and fixing before 2.4 is final.

**Comment by hollowdoor** [comment]
@photonstorm Did some one put the PIXI reference in? Seems strange that there would be a reference to a global dependency in the dependent.

**Comment by rodrigomaia17** [comment]
Updates?

**Comment by galarant** [comment]
tried this recently with Phaser 2.4.4 and browserify still shits itself on PIXI. If I have time over the holiday season I hope to address this and send a PR as an Xmas present to the Phaser community =)

**Comment by D34THWINGS** [comment]
Is anyone here can make a TL;DR on how to make it work with browserify. I read from the beginning but everything seems to be hacky. I saw instructions in the README for Webpack but doesn't help much for browserify. I already have a pretty huge stack built with browserify so i don't want to change my build system for the moment. The error i'm getting is:
```
phaser.js:23083 Uncaught ReferenceError: PIXI is not defined
```
If someone explain it right, I'll make a PR to add to the README so that no-one will have to ask on this post anymore

**Comment by konsumer** [comment]
It's looking for pixi to be defined globally. The proper way to fix this is to define the requirement, at the top of any file that references `PIXI`:

```
var PIXI = require('pixi.js');
```

The quick hack way is to monkey-patch it into the window, before you require phaser:

```
window.PIXI = require('pixi.js');
```

You will probably still need to monkey-patch all the phaser stuff into the global `Phaser` object. You can see an example, [here](https://github.com/notnullgames/phaser) where I actually track all the external & internal dependencies on a per-file basis.

**Comment by D34THWINGS** [comment]
I wish i made it to work with `browserify-shiw` but i just can't seem to find anything that works at all. I'll stick with the monkey-patch for now as i don't want to lost time with Phaser's wrong UMD definitions. I really love this framework but I find it so sad that the foundation of the framework, the dependency resolution is done so wrong. It could be easier for everyone to build their custom version of Phaser if every module was declared in UMD with proper resolution of dependencies. The best exemple I have for that is `lodash`. You just require the files you want in your build and that's it, no need for cloning and custom grunt task, it works with CommonJS/AMD/Window like a charm. I really want this to be in the v4.

**Comment by photonstorm** [comment]
There isn't a single module in Phaser, and never has been. It would require re-coding the entire thing from scratch, every single class, every single file. This is not something to be undertaken lightly, and I'm dubious of the merit of doing it at all, seeing as that's how Lazer is being built.

**Comment by the-simian** [comment]
I can't wait for Lazer, and we you're doing your best :)

**Comment by galarant** [comment]
@D34THWINGS I've gone back and forth on this for a long time and have dug into many threads on the topic. In short, @photonstorm has given the best answer available. As I understand it, the `Phaser` team has made so many modifications to their own custom fork of `PIXI` that it's essentially a different package at this point, and there is no browserify magick that will make the npm version of those two packages work together.

You can still use `Phaser` as an npm package, but just do it like this:

1. Install `Phaser` as an npm package: `npm install --save phaser`

2. from your project root, create a `/static/vendor` folder and add a symlink to your node_module:
`phaser -> ../../node_modules/phaser`

3. In your `index.html` just inject `Phaser` into the global scope by pointing to the symlink:

```
  <body style="margin: 0; padding: 0;">
    <!-- Have to include Phaser via script tag due to an incompatibility with Browserify -->
    <script type="text/javascript" src="/static/vendor/phaser/dist/phaser.min.js" defer></script>

    <script type="text/javascript" src="static/dist/bundle.js" defer></script>
  </body>
```

Then you can just refer to the `Phaser` object anywhere in your application, and the browser will recognize it since it's part of the global scope. But since it's still just a package, you can avoid adding the source to your repo etc.

Granted this approach is not aesthetically perfect, but speaking from experience it's a much better use of your time to simply punt on this issue for now and focus on building your game.

**Comment by D34THWINGS** [comment]
@galarant i'd better stick with the window hack for now because if i include it in my index.html, i will have to do a custom task to copy Phaser somewhere in my build from the `node_modules` then modify the name file for cache busting purpose if phaser is updated and also replace the relative path to the file to an absolute path to my Akamai CDN like I do with every single assets i have, and that's kind of work i can't afford for now. As you said, i need to focus on making the game, thanks for the advices !

Thanks @photonstorm for your work and sorry for bringing back old issues from the dead. I did a lot of development in Node and built huge frontend webapps but never seen libraries without proper UMD, that's why it surprised me, but I understand that it's not top priority. The JavaScript scene has a huge churn and tools come and go really fast, that's truly annoying.

**Comment by konsumer** [comment]
@photonstorm I did manage to do the modular thing in my fork with (which is 1486 commits behind photonstorm:master,) and it does work. I traced the concat-order you are using in your build system, turned those into requires, and defined PIXI & Phasor wherever it was needed (at the top of many files.) A similar idea could be applied to this repo, but I couldn't figure out what version to apply the changes to, and it sounded like it would duplicate other efforts you have going on.

**Comment by konsumer** [comment]
You can test it out by downloading it, running `npm install` and `npm run full-min` which will build phaser.js & phaser.min.js

**Comment by pbj-time** [comment]
hah looks like @konsumer actually achieved the task I wanted to do four months ago but gave up on. Awesome work!!

**Comment by konsumer** [comment]
Thanks! It's outdated, but fairly easy to redo. Basically put these at the top of every file:

```
var PIXI = require('pixi.js'); // npm install --save pixi.js
var Phasor = require('../Phasor.js'); // whatever the location is relative to the file you are in
```
and then make a commonjs entry-point like [mine](https://github.com/notnullgames/phaser/blob/master/src/entry_points/full.js). I based that on the current build stuff to figure out the right order. You can make multiple entry points for all the different versions of built files you want, but also, you can just include the files directly in your browserify/webpack project.

**Comment by konsumer** [comment]
It relies on the trick that commonjs keeps a singleton reference to the object in module.exports, so anywhere that you include Phasor.js, you are getting the same object (so you can monkey-patch new stuff into it)

**Comment by hayesmaker** [comment]
just add a script tag to ur html to add Phaser. It saves you having to
recompile 100,000lines of phaser code each time you browserify. And it
works.

**Comment by D34THWINGS** [comment]
@hayesmaker I don't recompile Phaser each time since I marked it as external in my build. I have a second build for my vendors that I run only once at the start of my dev task and it works like a charm. That's how i do my dev build :
```js
return browserify(options)
    .transform('babelify')
    .external(vendors);
```
And for my vendors build :
```js
return browserify()
    .require(vendors);
```

@konsumer when I was reading the thread i saw your fork and it was a great job but as you said it's outdated. And @photonstorm said that you shouldn't use the `pixi.js` repo since Phaser has a very custom version of PIXI, so the require of PIXI should also be relative. I think that the best way to achieve this is to fix the UMD. I'll try to make a POC this weekend on a fork. I think it could be more trivial than we think.

Here's an example, thats how Phaser uses UMD at the moment:
```js
(function (root) {
    var Phaser = {};
    // ... Phaser code goes here

    if (typeof exports !== 'undefined') {
        if (typeof module !== 'undefined' && module.exports) {
            exports = module.exports = Phaser;
        }
        exports.Phaser = Phaser;
    } else if (typeof define !== 'undefined' && define.amd) {
        define('Phaser', (function() { return root.Phaser = Phaser; })() );
    } else {
        root.Phaser = Phaser;
    }

    return Phaser;
}).call(this);
```

But the proper way to it is:

```js
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    define(['./pixi'], factory);
  } else if (typeof exports === 'object') {
    module.exports = factory(require('./pixi'));
  } else {
    root.Foo = factory(root.PIXI);
  }
}(this, function(PIXI) {
  var Phaser = {};
  // ... Phaser code goes here
  return Phaser;
}));
```

Using the factory pattern is way more efficient to handle dependencies for everything. And you don't have to do this on your own, there's some (grunt)[https://www.npmjs.com/package/grunt-umd] and (gulp)[https://www.npmjs.com/package/gulp-umd] plugins that can do that. You juste have to tell for each file what it depends on and everything will be wrapped up in the end so no pollution nor conflicts on the global scope can happen.

**Comment by D34THWINGS** [comment]
Also the UMD shouldn't wrap the whole code but each file so that each file can resolve dependencies on it's own. You will not have to change anything in the custom building feature since you'll have to concat all files in the right order because UMD wrapping doesn't solve the problem of defining order. The only thing that will change is the intro/outro that will no longer be required.
