### ISSUE TITLE
PIXI.canUseNewCanvasBlendModes is not a function

### ISSUE THREAD

**Issue by TonyPL** [photonstorm/phaser#2905]
Hello,

I was trying to make "ParticleStorm" plugin work with newest Phaser 2.7.1CE but it seems has a lot of references to custom PIXI build.
https://phaser.io/shop/plugins/particlestorm

Its working well with latest official Phaser 2.6.2.

Here is a call stack that you initially can get while trying to initialize the plugin.

Uncaught TypeError: PIXI.canUseNewCanvasBlendModes is not a function

Phaser.ParticleStorm	@	phaser.min.js:32
add	@	phaser.min.js:10
loadComplete	@	phaser.min.js:10
preUpdate	@	phaser.min.js:10
updateLogic	@	phaser.min.js:11
update	@	phaser.min.js:11
updateRAF	@	phaser.min.js:18
window.requestAnimationFrame.forceSetTimeOut._onLoop	@	phaser.min.js:18

As any way it can be solved?

**Comment by photonstorm** [comment]
Hi - Yeah you can. This issue should help: https://github.com/photonstorm/phaser/issues/2863 (let me know if it doesn't)
