### ISSUE TITLE
Retro Keyboard Example does not work in 3.52.0 

### ISSUE THREAD

**Issue by stonerich** [photonstorm/phaser#5564]
## Version

* Phaser Version: 3.52.0

Note: The same example works when selecting  version 3.51.0

* Operating system: macOS Bug Sur

* Browser: Chrome Version 88.0.4324.150 

## Description

Intented behavior: See a starfield and score list
Actually Happens: Black window,  the following error in console

BlitterWebGLRenderer.js:35 Uncaught TypeError: src.setRenderDepth is not a function
    at BlitterWebGLRenderer [as renderWebGL] (BlitterWebGLRenderer.js:35)
    at WebGLRenderer.render (WebGLRenderer.js:2494)
    at CameraManager.render (CameraManager.js:607)
    at Systems.render (Systems.js:405)
    at SceneManager.render (SceneManager.js:587)
    at Game.step (Game.js:491)
    at TimeStep.step (TimeStep.js:599)
    at step (RequestAnimationFrame.js:116)

## Example Test Code

http://phaser.io/examples/v3/view/input/keyboard/retro-leaderboard#

**Comment by photonstorm** [comment]
Thank you for spending time reporting this issue. However, we've already fixed this in the `master` branch of Phaser and it will be part of the next official release. You can track what's already been fixed by searching closed issues, or by looking at the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md).
