### ISSUE TITLE
Games work with the old version 2.0.6. But they get this error after switching to 2.4.2

### ISSUE THREAD

**Issue by shohan4556** [photonstorm/phaser#1971]
TypeError: this.scale.setScreenSize is not a function

here is my github repository of the game - https://github.com/shohan4556/Space-Jam/tree/gh-pages

**Comment by Pajamaman** [comment]
That method was deprecated in 2.2.0. You should use `this.scale.updateLayout` instead.

**Comment by shohan4556** [comment]
what will be the value of the property 'true' or 'false' ?

**Comment by Pajamaman** [comment]
That's because of your `scaleMode`. From line 16 of Boot.js:

    this.scale.scaleMode = Phaser.ScaleManager.SHOW_ALL;

If you don't want it to scale at all, you can use `NO_SCALE` instead, like this:

    this.scale.scaleMode = Phaser.ScaleManager.NO_SCALE;

**Comment by shohan4556** [comment]
:+1:

**Comment by Pajamaman** [comment]
You should close this issue then. I think @photonstorm has his hands full.
